### ISSUE TITLE
Build: workspace cargo check fails because ShapingEngine calls missing insert_queue

### ISSUE THREAD

**Issue by AusAgentSmith** [ZerosAndOnesLLC/AiFw#582]
`cargo check --workspace` fails in `aifw-core/src/shaping.rs:167`:

```text
error[E0599]: no method named `insert_queue` found for reference `&ShapingEngine`
```

`ShapingEngine::update_queue()` calls `self.insert_queue(&config).await?`, but the implemented helper is `insert_queue_on(...)` at line 278. The workspace cannot compile until the call is corrected (or a wrapper is restored).

Reproduced 2026-07-22 with `cargo check --workspace` on commit `719d033`.

**Comment by mack42** [comment]
Fixed on the PR #580 branch (commit 34f4036): the merge with main had kept a call to insert_queue after main renamed it to insert_queue_on — a semantic merge conflict git resolved cleanly but couldn't compile. Merged with #580; workspace cargo check has been green since.
